### PR TITLE
Update logos & colors

### PR DESCRIPTION
**Pull request by MythicalFish**

### CODE REVIEW

**Comment by bentsherman** [comment]
Shall we add fonts while we're at it?

**Comment by ewels** [comment]
- [ ] New logo in the social share card
- [ ] Missing images on the ["about us" page](https://deploy-preview-145--nextflow-staging.netlify.app/about-us)
- [ ] (If possible) - Degular font on headings. They're on the [updated Nextflow docs PR](https://github.com/nextflow-io/nextflow/pull/4407) now, so would be nice to have consistency if possible.

**Comment by bentsherman** [comment]
I was able to grab the Inter font from Google Fonts

**Comment by ewels** [comment]
> I was able to grab the Inter font from Google Fonts

Can probably just use directly from Google Fonts without needing to bother getting the font source files. At least for nextflow.io.

**Comment by ewels** [comment]
Ah, that's what you did on the docs too. Nice.

**Comment by ewels** [comment]
Looking good! The font isn't working for me though? (iOS safari)

also it's the old logo on the about page:
image

Both pretty minor though. Mergeable in this state and can fix those points another day if needed. Thanks @MythicalFish!

**Comment by bentsherman** [comment]
Shall we use the Inter font for body? I just embedded a link from google fonts: https://github.com/nextflow-io/nextflow/blob/7a13b18bd16e71670e5872108b65f6b4fe112c05/docs/_static/theme.css#L2

**Review by ewels — APPROVED** [review]

**Comment by ewels** [comment]
I'll merge first to get this out, let's add Inter in a separate PR @bentsherman @MythicalFish  👍🏻

**Pull request merged**
