### PR TITLE
Add nextflow fig post

### PR DESCRIPTION
**Pull request by mribeirodantas**
Ready to merge (On Thursday, 22th, Sept).

Screenshot of blog index
Screen Shot 2022-09-16 at 22 57 46

Screenshot of blog post
Screen Shot 2022-09-16 at 22 58 17
Screen Shot 2022-09-16 at 22 58 26
Screen Shot 2022-09-16 at 22 58 31

### CODE REVIEW

**Review by ewels — APPROVED** [review]
Great!

**Comment by pditommaso** [comment]
Let's use bit more descriptive name for image files instead of `demo1.gif` and and `demo2.gif`

**Comment by mribeirodantas** [comment]
> Let's use bit more descriptive name for image files instead of `demo1.gif` and and `demo2.gif`

Done 😄

**Comment by pditommaso** [comment]
Gave a try to this. Animation is not starting for me. Also there are two broken image links

**Comment by mribeirodantas** [comment]
> Gave a try to this. Animation is not starting for me. Also there are two broken image links

I'm sorry. It's fixed now 😄

**Comment by ewels** [comment]
Apologies from me too, didn't test locally for my review 🙄 Will make sure to do so in the future..

**Comment by ewels** [comment]
Ah I guess it broke after I left my review. Should have kept quiet 😆

**Comment by mribeirodantas** [comment]
It's ready to merge 😄 (just updated the correct date)

**Comment by pditommaso** [comment]
I think animation after `brew install --cask fig` can be removed. I find it a bit confusing, because the context is about nextflow instead shows some random commands

**Comment by pditommaso** [comment]
damn, it works!  😆

**Pull request merged**
