### PR TITLE
Justice image 

### PR DESCRIPTION
**Pull request by iamamofa**
<AmbassadorCard
        name="Justice Ohene Amofa"
        img="justice.jpg"
        country="Gha"
        github="Iamamofa"
        linkedin="justice-ohene-amofa-349b44173"
        twitter="I_am_amofa"
      >
        Justice is a Bioinformatician at the <a href="https://noguchi.ug.edu.gh" target="_blank"
          >Noguchi Memorial Institute For Medical Research</a
        >. He develops pipelines and workflows for bioinformatics analysis  and software for desktop and web applications  for work and he is  on the <a
          href="https://pangens.org"
          target="_blank">PANGenS Project</a
        >.
      </AmbassadorCard>

### CODE REVIEW

**Comment by mribeirodantas** [comment]
Hey @iamamofa. Could you please shorten your bio a bit? Currently it's a bit long and then the social media icons disappear in the box. Make sure to `git pull`, as I committed some improvements to your PR. You can check the preview [here](https://deploy-preview-270--nextflow-staging.netlify.app/).

**Comment by iamamofa** [comment]
> Hey @iamamofa. Could you please shorten your bio a bit? Currently it's a bit long and then the social media icons disappear in the box. Make sure to `git pull`, as I committed some improvements to your PR. You can check the preview [here](https://deploy-preview-270--nextflow-staging.netlify.app/).

**Comment by iamamofa** [comment]
updated with new contents . Kindly check it out

**Review by mribeirodantas — APPROVED** [review]

**Comment by mribeirodantas** [comment]
Great, Amofa! LGTM

**Pull request merged**
