### PR TITLE
Remove outdated CLA page

### PR DESCRIPTION
**Pull request by ewels**
Now redundant after the chance to Apache, which happened ages ago.

### CODE REVIEW

**Comment by ewels** [comment]
Or maybe, not...? https://www.nextflow.io/cla.html

Not sure why it's still there?

**Comment by bentsherman** [comment]
Looks like the build process uploads each file individually, so probably the old CLA page wasn't deleted

**Comment by ewels** [comment]
ok, I can't do anything about this (until we change how the site is hosted 👀 ).

@pditommaso I think you need to go into AWS and manually delete the built HTML file to remove this..

**Comment by pditommaso** [comment]
But the publish just sync the output dir to S3. It should be enough to remove it from this repo 

https://github.com/nextflow-io/website/blob/master/Makefile#L2-L7

**Comment by ewels** [comment]
I think it needs the `--delete` flag..

**Comment by ewels** [comment]
Opened a PR in https://github.com/nextflow-io/website/pull/130 - the `--delete` flag was already there for the sync command for the docs..

**Pull request merged**
