### PR TITLE
Add Nicolas' post on nf-schema

### PR DESCRIPTION
**Pull request by mribeirodantas**
Signed-off-by: Marcel Ribeiro-Dantas <mribeirodantas@seqera.io>

### CODE REVIEW

**Review by vdauwera — CHANGES_REQUESTED** [review]
The post looks great overall but the first paragraph doesn’t work as a summary on its own (as displayed on the blog landing page). It’s confusing to read a title that suggests it’s about nf-schema but then the summary looks like it’s only about nf-validation. Because of the constraint of how the posts are displayed on that landing page, we need to always make sure that first paragraph works as a standalone blurb.

**Comment by mribeirodantas** [comment]
Thanks for the feedback, @vdauwera. What do you think about it now?

**Review by vdauwera — COMMENTED** [review]
Ah that’s much better, thank you. I might recommend something like “check out nextflow’s newest plugin” (revamped is a bit confusing, I understand it’s revamped compared to nf-validation but it muddies the water a bit) but otherwise LGTM.

**Comment by ewels** [comment]
> Because of the constraint of how the posts are displayed on that landing page

Remember I made it work like this again when you guys all requested 😉 If it's regularly annoying it's pretty easy to add a new YAML frontmatter field for this. Just let me know.

**Comment by vdauwera** [comment]
> > Because of the constraint of how the posts are displayed on that landing page
> 
> Remember I made it work like this again when you guys all requested 😉 If it's regularly annoying it's pretty easy to add a new YAML frontmatter field for this. Just let me know.

No it's good, we should aim for the intro paragraph to function as a synopsis anyway. It helps hook the reader and provide clarity on what the post is about.

**Pull request merged**
