### PR TITLE
Summit call for abstracts

### PR DESCRIPTION
**Pull request by ewels**
Draft blog post for the Summit / call for abstracts.

Wasn't totally sure if I should commit the results of running `./jbake` to the repo or not, I did it in a separate commit though so shout if I should revert that.

Phil

### CODE REVIEW

**Review by pditommaso — COMMENTED** [review]
Only the markdown and related assets e.g. images should be added. The HTML is generated by GHA

**Comment by ewels** [comment]
Ok, I'll rebase when I get to a keyboard 👍🏻

Should the `output` directory be removed from the repo then?

**Comment by pditommaso** [comment]
> Should the output directory be removed from the repo then?

umm, no. because the nextflow docs is generated manually 😵‍💫

**Comment by ewels** [comment]
ok, I'm going to stop asking questions and just do what you say 😆

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
Vamos!

**Pull request merged**
