### PR TITLE
Post about Running CAW with Singularity images

### PR DESCRIPTION
**Pull request by MaxUlysse**
Hi,

I'm hoping I'm doing it the right way.
Sorry for taking so long to write this post.
I hope you'll like it.
If there is any changes to be done, don't hesitate to tell me.

All the best,
Maxime

### CODE REVIEW

**Comment by pditommaso** [comment]
Fantastic! I will merge and the eventually propose some changes. Thanks!

**Comment by pditommaso** [comment]
I've made some minor formatting changes and short intro. See https://github.com/nextflow-io/website/commit/e0b91a8a5667ba8d812ce4c8b47017eb37c111f4. If you are happy I will publish it.

**Comment by MaxUlysse** [comment]
Looks perfect to me.
Thanks a lot

**Comment by pditommaso** [comment]
👍

**Pull request merged**
