### PR TITLE
Update pipeline examples to DSL2

### LINKED ISSUE #40: Update nextflow examples to DSL2
Nextflow example on website should be updated to DSL2

* https://www.nextflow.io/example1.html
* https://www.nextflow.io/example2.html
* https://www.nextflow.io/example3.html
* https://www.nextflow.io/example4.html

### PR DESCRIPTION
**Pull request by bentsherman**
Resolves #40 

This PR updates the workflow examples to DSL2.

### CODE REVIEW

**Comment by pditommaso** [comment]
This is is nice! think we should just add a disclaimer that it requires Nextflow 22.04.0 or later.

Also maybe it's time up update the rnaseq pipeline with [this](https://github.com/nextflow-io/rnaseq-nf/blob/master/main.nf) instead of the [old rnatoy](https://github.com/nextflow-io/rnatoy)

**Comment by bentsherman** [comment]
Done. I replaced rnatoy with a minimal version of rnaseq-nf, since it uses modules now.

**Comment by pditommaso** [comment]
OK, nice. I'll merge this once we release 22.04 next week 👍

**Comment by ewels** [comment]
@pditommaso bump - should be ok to merge now 👍🏻

**Comment by pditommaso** [comment]
The Blast example links to a [script using the old](https://github.com/nextflow-io/blast-example/blob/master/main.nf) syntax. Good opportunity to update and test it

**Comment by bentsherman** [comment]
I have pushed a PR to the blast-example repo: https://github.com/nextflow-io/blast-example/pull/3

We should resolve the issue I brought up there before merging this PR.

**Comment by pditommaso** [comment]
Great job, thanks

**Pull request merged**
