### PR TITLE
make publish: `aws s3 sync --delete`

### PR DESCRIPTION
**Pull request by ewels**
# DO NOT MERGE YET
See comment discussion below.

--

Continuation from https://github.com/nextflow-io/website/pull/129

### CODE REVIEW

**Comment by ewels** [comment]
wait, wait, wait - it's possible that adding `--delete` here will wipe out the documentation.

Looking at the makefile + github actions again, the GHA doesn't build the docs. So those won't be present in the first of the two sync steps. So `--delete` will wipe out the remote `docs` folder that isn't present locally.

This probably explains why the flag is there in one command and not the other. 

I think that this is probably not worth messing with now. Better to replace the website hosting completely and switch to a new fully automated build system.

So @pditommaso - you still need to go in to s3 and manually delete the CLA file for now, sorry.

**Comment by pditommaso** [comment]
What's the file to be deleted?

**Comment by ewels** [comment]
`cla.html`

https://www.nextflow.io/cla.html

**Comment by pditommaso** [comment]
Done!

```
» aws s3 rm s3://www2.nextflow.io/cla.html
delete: s3://www2.nextflow.io/cla.html

» aws s3 rm --recursive s3://www2.nextflow.io/cla
delete: s3://www2.nextflow.io/cla/NEXTFLOW-CLA-Entity.pdf
delete: s3://www2.nextflow.io/cla/NEXTFLOW-CLA-Individual.pdf
```

**Comment by ewels** [comment]
image

**Pull request closed without merging**
