### PR TITLE
Actually add buttons for the CFA on the summit page

### PR DESCRIPTION
**Pull request by ewels**
My local testing setup is now refusing to launch, so maybe worth double checking that this renders properly if possible.

After I added the links, the blog listing page was chopping up the button and giving weird effects. I tried adjusting the word limit cutoff but now can't test to see if I got it right 🤦🏻 

Hopefully it's ok..?? 🤞🏻

### CODE REVIEW

**Comment by pditommaso** [comment]
There's no real change in `templates/archive.ftl`, right?

**Comment by ewels** [comment]
> There's no real change in `templates/archive.ftl`, right?

Ah sorry, that's my editor cleaning trailing whitespace. Just one addition:

```html
						<#elseif post.title == "Nextflow Summit 2022" >
 							<#assign MAX = 140>
```

You can view the PR diff without whitespace-only changes [here](https://github.com/nextflow-io/website/pull/56/files?diff=unified&w=1#diff-799f605dc96a7f3c92654e9eba7f3b654f69d6c04946bd15adad71ca8915516d):

image

**Comment by ewels** [comment]
Managed to build + test using GitPod just now and looks fine to me 👍🏻

**Comment by pditommaso** [comment]
cool

**Pull request merged**
