### PR TITLE
Add Ambassador profile for Opeyemi Alayande

### PR DESCRIPTION
**Pull request by ycode-sh**

### CODE REVIEW

**Comment by mribeirodantas** [comment]
Hi @ycode-sh. You need to shorten your bio a bit, as it currently is pushing the icons outside the box view. You can check the preview [here](https://deploy-preview-269--nextflow-staging.netlify.app/our_ambassadors.html) (hover your mouse over your profile box to check). After you shorten it, you can check again the preview to make sure it's within the right length.

**Comment by mribeirodantas** [comment]
@ycode-sh ?

**Comment by mribeirodantas** [comment]
@ycode-sh Anything I can help you with to get through with this PR? :)

**Comment by ycode-sh** [comment]
I have made the neccessary cut. Thank you very much

**Comment by mribeirodantas** [comment]
It is still long. Check the printscreen below.
Captura de Tela 2024-09-04 às 19 57 14

**Comment by mribeirodantas** [comment]
I shortened it a bit. Can you confirm you're ok with it this way?

**Comment by ycode-sh** [comment]
I apologize for the incovenienes. Yes, I am okay with your edits

**Review by mribeirodantas — APPROVED** [review]

**Comment by mribeirodantas** [comment]
It's fien, no inconvenience at all 😉

**Pull request merged**
